// FILM.TIMELINE: the shot list and audio cue list for "The cell cycle and mitosis".
// Owner: storyboard. Human-readable plan: docs/storyboard.md. Visual rules: docs/art-bible.md.
// 120 bpm: a beat is 0.5 s (12 frames at 24 fps). Every shot boundary sits on the beat grid.
(function () {
  'use strict';
  const FILM = window.FILM;

  FILM.TIMELINE = {
    title: 'The cell cycle and mitosis',
    bpm: 120,
    duration: 30,
    fps: 24,
    width: 1080,
    height: 1920,
    shots: [
      { id: 'hero-cell', file: '01-hero-cell.js', start: 0, end: 2, mode: 'illustrated', title: 'Cold open: one cell among many',
        transitionIn: { kind: 'cut', dur: 0 },
        brief: 'One body cell huge in frame on G1 among neighbours cut by the edges, over cream and yellow stripes; nucleus with the four chromosomes (two pairs, chromoA long blue, chromoB short rust), six mitochondria, ribosome stipple. Frame 0 fully drawn. The cell breathes on the 0.5 s beat as yellow and magenta rings burst from the nucleus.' },
      { id: 'cell-blueprint', file: '02-cell-blueprint.js', start: 2, end: 4.5, mode: 'schematic', title: 'Inside: nucleus, 23 pairs, the cycle',
        transitionIn: { kind: 'cut', dur: 0 },
        brief: 'A spark on near-black navy, then the blueprint builds: the cell outline on G1, the nucleus lattice, four glow-dot chromosomes, a tally of 46 ticks in 23 pairs on an arc, and the cycle glyph G5 drawn at (900, 300). This shot owns the canonical cycle-glyph helper.' },
      { id: 'growth', file: '03-growth.js', start: 4.5, end: 7, mode: 'illustrated', title: 'The cell grows',
        transitionIn: { kind: 'cut', dur: 0 },
        brief: 'The paper cell on G1 grows on four beats (radius 380 to 440), new mitochondria draw in two at a time, ribosome stipple thickens, a ruler and bracket measure it, a tally ring counts. The cycle glyph lights its grow sector. Chromosome number unchanged.' },
      { id: 'dna-copy-blueprint', file: '04-dna-copy-blueprint.js', start: 7, end: 9.5, mode: 'schematic', title: 'The DNA is copied',
        transitionIn: { kind: 'cut', dur: 0 },
        brief: 'Blueprint nucleus; push 6x into one chromosome as a double helix, it unzips and new strands draw in magenta so two identical helices lie side by side; pull back and each of the four chromosomes becomes an X of two joined copies on G2, one per 16th. Copy sector of the glyph lights.' },
      { id: 'copies-joined', file: '05-copies-joined.js', start: 9.5, end: 11.5, mode: 'illustrated', title: 'Two identical copies, joined',
        transitionIn: { kind: 'cut', dur: 0 },
        brief: 'Match cut onto the four inked X chromosomes on G2 inside the paper cell; centromere rings pulse, a bracket labels chromosome, an arc joins the two identical arms; on the last beat the chromosomes condense.' },
      { id: 'membrane-breaks', file: '06-membrane-breaks.js', start: 11.5, end: 13.5, mode: 'illustrated', title: 'Mitosis begins: the nuclear membrane goes',
        transitionIn: { kind: 'flash', dur: 0.125 },
        brief: 'The hinge at T 12.0: cream flash, the nuclear membrane bursts into 24 drifting dashes and fades, the chromosomes condense and drift to the equator, two poles appear, the cell begins to elongate toward G3. Bracket labels nucleus.' },
      { id: 'spindle-blueprint', file: '07-spindle-blueprint.js', start: 13.5, end: 16, mode: 'schematic', title: 'Fibres line the chromosomes up',
        transitionIn: { kind: 'cut', dur: 0 },
        brief: 'Blueprint of the spindle on G3: two poles with radial ticks, fibres shoot from each pole to each centromere on 32nds, free fibres fan out, the four X chromosomes snap onto the metaphase plate y 900 and stand upright; a bracket measures the plate.' },
      { id: 'pull-apart', file: '08-pull-apart.js', start: 16, end: 19, mode: 'illustrated', title: 'The copies are pulled apart',
        transitionIn: { kind: 'cut', dur: 0 },
        brief: 'Paper cell elongated on G3 with inked fibres; the fibres tighten, each centromere splits, and the copies travel to opposite poles on twos as single-arm chromosomes, trailing arms in a V; pole rings pulse on arrival. Bracket labels spindle.' },
      { id: 'two-nuclei-blueprint', file: '09-two-nuclei-blueprint.js', start: 19, end: 21.5, mode: 'schematic', title: 'Two new nuclei, the cell pinches',
        transitionIn: { kind: 'cut', dur: 0 },
        brief: 'Blueprint: a lattice membrane draws round each chromosome set at the poles, the fibres dissolve, the chromosomes relax, and the cell outline pinches at the equator into the G4 two-lobe shape with magenta furrow rings.' },
      { id: 'two-cells', file: '10-two-cells.js', start: 21.5, end: 25.5, mode: 'illustrated', title: 'Two cells, pull back to the tissue',
        transitionIn: { kind: 'flash', dur: 0.125 },
        brief: 'Flash onto G4; the neck closes and two daughter cells seal, an arc labels them identical, a tally flips 1 to 2; then the camera pulls back to 0.45 as two dozen neighbour cells pop in around them, several mid-division.' },
      { id: 'loop', file: '11-loop.js', start: 25.5, end: 30, mode: 'illustrated', title: 'One daughter becomes the hero: the cycle loops',
        transitionIn: { kind: 'cut', dur: 0 },
        brief: 'From the wide tissue the camera pushes into the lower daughter until it sits exactly on G1 with the shot-01 composition; its chromosomes relax into the G1 shapes, the wordmark fades in, a yellow ring pulses on the last beat, and the cycle glyph completes.' },
    ],
    cues: [
      { t: 0, kind: 'hit', note: 'Hook: felt kick, low D minor pad swell; kalimba motif D5 F5 A5 E5 on 8ths' },
      { t: 0.5, kind: 'sfx', note: 'Ring burst: upward glass gliss 200 ms and a soft crash' },
      { t: 2, kind: 'cut', note: 'Blueprint drop: everything out except a glassy sine ping on D6 with long reverb' },
      { t: 2.5, kind: 'sfx', note: 'Four rising bell pings on 16ths D5 F5 A5 D6' },
      { t: 3, kind: 'sfx', note: '23 paired plips on 32nds climbing D minor, quiet, panned along the arc, to 3.75' },
      { t: 4, kind: 'hit', note: 'Soft gong D3; kalimba motif returns on 8ths' },
      { t: 4.5, kind: 'cut', note: 'Brush pattern on 8ths; pad rises a third' },
      { t: 5, kind: 'sfx', note: 'Woody tock and a chew grain (mitochondria draw in); plip per tally tick' },
      { t: 5.5, kind: 'sfx', note: 'Tock and chew grain; plip' },
      { t: 6, kind: 'sfx', note: 'Tock and chew grain; plip' },
      { t: 6.5, kind: 'sfx', note: 'Warm glass ring A5 for the nucleus pulse' },
      { t: 7, kind: 'cut', note: 'Blueprint drop, sine ping D6' },
      { t: 7.25, kind: 'swell', note: 'Rising reverse swell under the push-in' },
      { t: 7.75, kind: 'sfx', note: 'Zip: fast downward high-passed noise sweep as the helix unzips' },
      { t: 8, kind: 'sfx', note: 'Bell arpeggio D minor pentatonic in 16ths tracking the new strands' },
      { t: 9, kind: 'sfx', note: 'Ping D5 (A1 becomes an X)' },
      { t: 9.125, kind: 'sfx', note: 'Ping F5 (A2)' },
      { t: 9.25, kind: 'sfx', note: 'Ping A5 (B1)' },
      { t: 9.375, kind: 'sfx', note: 'Ping D6 (B2)' },
      { t: 9.5, kind: 'cut', note: 'Kick and pad return; kalimba motif' },
      { t: 10, kind: 'sfx', note: 'Four soft tocks on 32nds as the centromere rings pulse' },
      { t: 10.5, kind: 'sfx', note: 'Glass gliss up a fifth for the identical arc' },
      { t: 11, kind: 'sfx', note: 'Low thud and a tightening creak grain (condense)' },
      { t: 12, kind: 'hit', note: 'THE HINGE: whump with sub drop, crash, everything ducked; pad modulates to D major' },
      { t: 12.5, kind: 'sfx', note: 'Dry tock' },
      { t: 13, kind: 'sfx', note: 'Slow rising glide as the chromosomes gather' },
      { t: 13.5, kind: 'cut', note: 'Blueprint drop, sine ping' },
      { t: 14, kind: 'sfx', note: 'Pizzicato plucks on 32nds rising, one per fibre from the top pole' },
      { t: 14.5, kind: 'sfx', note: 'Pizzicato plucks on 32nds falling, one per fibre from the bottom pole' },
      { t: 15, kind: 'sfx', note: 'Bright ting A5 as the chromosomes snap to the plate' },
      { t: 15.5, kind: 'sfx', note: 'Tremolo shimmer' },
      { t: 16, kind: 'cut', note: 'Kick and pad; kalimba motif in D major' },
      { t: 16.5, kind: 'sfx', note: 'Creak as the fibres tighten' },
      { t: 17, kind: 'sfx', note: 'Downward whoosh and a split crack; ratchet of plips on 16ths as the copies travel' },
      { t: 18.5, kind: 'sfx', note: 'Two glass rings A5 then D6, one per pole' },
      { t: 19, kind: 'cut', note: 'Blueprint drop, sine ping' },
      { t: 19.5, kind: 'sfx', note: 'Soft bell arpeggio (upper membrane)' },
      { t: 19.75, kind: 'sfx', note: 'Soft bell arpeggio (lower membrane)' },
      { t: 20, kind: 'sfx', note: 'Cave-reverb wash as the fibres dissolve' },
      { t: 20.5, kind: 'sfx', note: 'Low pulse, tightening creak, tock (furrow)' },
      { t: 21, kind: 'sfx', note: 'Low pulse, creak, tock (furrow)' },
      { t: 21.5, kind: 'hit', note: 'Division hit: whump, crash, two-note answer D5 A5 with the kalimba' },
      { t: 22, kind: 'sfx', note: 'Glass gliss for the arc; plip for the tally' },
      { t: 22.5, kind: 'swell', note: 'Rising pad and marimba pattern in 16ths to 25.0; one plip per cell popping in, panned by position' },
      { t: 25, kind: 'hit', note: 'Warm gong D3' },
      { t: 25.5, kind: 'cut', note: 'Pad thins; kalimba motif slows to quarter notes' },
      { t: 26, kind: 'swell', note: 'Long rising reverse swell under the push-in to 29.0; heartbeat kick on each beat, growing' },
      { t: 29.5, kind: 'sfx', note: 'Glass ring D6 carrying across the loop seam into the 0.0 hit; level matches bar 1' },
    ],
  };
})();
