# -*- coding: utf-8 -*-
"""Audit and top up related_media for ONE rebuilt AQA Drama set-play unit.

The rebuild keeps the lesson rows, so each row already carries related media —
including the real Lesson Podcast entry, which must survive untouched. This
script therefore MERGES rather than replaces:

  1. every existing item is verified (YouTube through oEmbed, everything else
     through an HTTP fetch with a browser user agent);
  2. items on the manual drop list are removed — that list is where "this item
     is about a different play" decisions live, because no HTTP check can spot
     an alive link pointing at the wrong work;
  3. verified candidates generated by the driver's media stage are appended,
     deduplicated by URL, until the lesson carries at least the floor;
  4. categories are re-ordered canonically and empty ones dropped.

Nothing is written without --apply. Without it the script prints the audit and
writes the report, so the drops can be read before anything changes.

Usage:
  python scripts/api_build/drama_media_merge.py the-empress
  python scripts/api_build/drama_media_merge.py the-empress --apply
"""
import argparse
import io
import json
import os
import re
import sys
from concurrent.futures import ThreadPoolExecutor

import requests

sys.stdout.reconfigure(encoding="utf-8", errors="replace")
REPO = r"C:\Users\tshau\Documents\Study Vault"
sys.path.insert(0, os.path.join(REPO, "scripts"))
from lib.supabase_client import get_client  # noqa: E402

UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/124.0 Safari/537.36")
TIMEOUT = 12
FLOOR = 8

CATEGORY_ORDER = ["Podcasts", "Videos & Channels", "Movies", "TV Shows",
                  "Documentaries", "Study Tools"]
CATEGORY_EMOJI = {
    "Podcasts": "\U0001F399\uFE0F",
    "Videos & Channels": "\U0001F4FA",
    "Movies": "\U0001F3AC",
    "TV Shows": "\U0001F4FA",
    "Documentaries": "\U0001F3AC",
    "Study Tools": "\U0001F6E0\uFE0F",
}

UNITS = {
    "the-empress": "d7a76fb7-7f0f-4e51-9c01-1349426ee100",
    "a-taste-of-honey": "6e5bf995-9b84-4e3f-8a59-80c6616e4b6a",
    "things-i-know-to-be-true": "5dba787f-1506-448c-92b8-f2cfe08d0d78",
}

YT_ID = re.compile(r"(?:v=|youtu\.be/|/embed/|/shorts/)([A-Za-z0-9_-]{11})")


def is_youtube(url):
    return "youtube.com" in url or "youtu.be" in url


def check(url):
    """Return (status, note). status is 'ok', 'dead' or 'unknown'."""
    try:
        if is_youtube(url) and YT_ID.search(url):
            r = requests.get("https://www.youtube.com/oembed",
                             params={"url": url, "format": "json"},
                             headers={"User-Agent": UA}, timeout=TIMEOUT)
            if r.status_code == 200:
                d = r.json()
                return "ok", "%s | %s" % (d.get("title", "")[:80],
                                          d.get("author_name", "")[:40])
            if r.status_code in (401, 403, 404):
                return "dead", "oembed %d" % r.status_code
            return "unknown", "oembed %d" % r.status_code
        r = requests.get(url, allow_redirects=True, timeout=TIMEOUT, stream=True,
                         headers={"User-Agent": UA, "Accept": "*/*"})
        code = r.status_code
        r.close()
        if code < 400:
            return "ok", str(code)
        if code in (403, 405, 429):
            return "unknown", "%d (blocks bots)" % code
        return "dead", str(code)
    except requests.exceptions.Timeout:
        return "unknown", "timeout"
    except Exception as e:
        return "unknown", str(e)[:60]


def load_drops(play):
    """drop_urls  — alive links that point at the wrong work, or whose title and
                    URL disagree beyond repair. No HTTP check can find these.
    fixes       — url -> {title, description, category} corrections applied to a
                    kept item, for stored titles or categories that are wrong."""
    p = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                     "_drama_media_drops_%s.json" % play)
    if not os.path.exists(p):
        return set(), {}, {}
    d = json.load(io.open(p, encoding="utf-8"))
    return set(d.get("drop_urls", [])), d.get("reasons", {}), d.get("fixes", {})


def load_candidates(play):
    cfg_path = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                            "config_drama-aqa-%s.json" % play)
    cfg = json.load(io.open(cfg_path, encoding="utf-8"))
    p = os.path.join(cfg["run_dir"], "related_media.json")
    return json.load(io.open(p, encoding="utf-8")) if os.path.exists(p) else {}


def main(play, apply_changes):
    unit_id = UNITS[play]
    drop_urls, drop_reasons, fixes = load_drops(play)
    candidates = load_candidates(play)
    sb = get_client()
    rows = (sb.table("lessons")
            .select("id, lesson_number, title, related_media")
            .eq("unit_id", unit_id).order("lesson_number").execute()).data

    # one pass over every URL involved, checked in parallel
    urls = set()
    for r in rows:
        for cat in (r.get("related_media") or []):
            for it in cat.get("items", []):
                if it.get("title") != "Lesson Podcast" and it.get("url"):
                    urls.add(it["url"])
    for cid, cats in candidates.items():
        for cat in cats:
            for it in cat.get("items", []):
                if it.get("url"):
                    urls.add(it["url"])
    urls = sorted(urls)
    print("checking %d distinct URLs..." % len(urls))
    with ThreadPoolExecutor(max_workers=12) as ex:
        results = dict(zip(urls, ex.map(check, urls)))

    report = {"play": play, "checked": len(urls), "lessons": {}}
    for r in rows:
        n = r["lesson_number"]
        cid = "%s-L%02d" % (play, n)
        kept = {}
        dropped = []
        fixed = []
        podcast_item = None
        for cat in (r.get("related_media") or []):
            name = cat.get("category")
            for it in cat.get("items", []):
                url = it.get("url")
                if it.get("title") == "Lesson Podcast":
                    podcast_item = it
                    continue
                if not url:
                    continue
                if url in drop_urls:
                    dropped.append({"url": url, "title": it.get("title"),
                                    "why": drop_reasons.get(url, "manual drop")})
                    continue
                status, note = results.get(url, ("unknown", "not checked"))
                if status == "dead":
                    dropped.append({"url": url, "title": it.get("title"),
                                    "why": "dead link (%s)" % note})
                    continue
                fix = fixes.get(url)
                target = name
                if fix:
                    it = dict(it)
                    for k in ("title", "description"):
                        if fix.get(k):
                            it[k] = fix[k]
                    target = fix.get("category") or name
                    fixed.append({"url": url, "to": target, "title": it.get("title")})
                kept.setdefault(target, []).append(it)

        have = {it["url"] for items in kept.values() for it in items}
        added = []
        for cat in candidates.get(cid, []):
            name = cat.get("category")
            if name not in CATEGORY_ORDER:
                continue
            for it in cat.get("items", []):
                url = it.get("url")
                if not url or url in have or url in drop_urls:
                    continue
                status, note = results.get(url, ("unknown", "not checked"))
                if status != "ok":
                    continue
                total = sum(len(v) for v in kept.values())
                if total >= FLOOR and len(kept.get(name, [])) >= 3:
                    continue
                if len(kept.get(name, [])) >= 3:
                    continue
                kept.setdefault(name, []).append(it)
                have.add(url)
                added.append({"category": name, "url": url, "title": it.get("title")})

        out = []
        if podcast_item:
            pod = [podcast_item] + kept.pop("Podcasts", [])
            out.append({"category": "Podcasts", "emoji": CATEGORY_EMOJI["Podcasts"],
                        "items": pod})
        for name in CATEGORY_ORDER:
            if name == "Podcasts" and podcast_item:
                continue
            items = kept.get(name)
            if items:
                out.append({"category": name, "emoji": CATEGORY_EMOJI[name],
                            "items": items})
        total = sum(len(c["items"]) for c in out)
        report["lessons"][cid] = {"total": total, "dropped": dropped,
                                  "fixed": fixed, "added": added}
        flag = "" if total >= FLOOR else "   << BELOW FLOOR"
        print("  L%02d %-46s %2d items (-%d ~%d +%d)%s"
              % (n, r["title"][:46], total, len(dropped), len(fixed), len(added), flag))
        for d in dropped:
            print("        DROP %s — %s" % ((d["title"] or "")[:44], d["why"]))
        for f in fixed:
            print("        FIX  [%s] %s" % (f["to"], (f["title"] or "")[:52]))
        for a in added:
            print("        ADD  [%s] %s" % (a["category"], (a["title"] or "")[:52]))
        if apply_changes:
            sb.table("lessons").update({"related_media": out}).eq("id", r["id"]).execute()

    rp = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                      "_drama_media_report_%s.json" % play)
    io.open(rp, "w", encoding="utf-8").write(
        json.dumps(report, ensure_ascii=False, indent=1))
    print(("APPLIED" if apply_changes else "DRY RUN (pass --apply to write)")
          + " — report at " + rp)


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("play", choices=sorted(UNITS))
    ap.add_argument("--apply", action="store_true")
    a = ap.parse_args()
    main(a.play, a.apply)
