"""Build typed-recall cards from what a lesson already holds, into lessons.recall_cards.

Card kinds (docs/FLASHCARD_RULES.md rule 3 already prefers cloze; the judge makes the rest
gradeable, which the honesty tap never could):

  term        front = the glossary term            answer = its definition
  definition  front = the definition               answer = the term
  cloze       front = a lesson sentence with the term blanked   answer = the term (or number)

Caps per lesson: 1 term, 1 definition, 2 cloze (a glossary-term sentence first, then a
sentence containing a year or a number), and never a term the curated deck already tests
(its answer, or the subject of one of its questions), so a lesson lands at about 15 cards. Nothing is generated by a model; every answer
is text the lesson already teaches, so the fact-check that cleaned the lesson covers it.

  python scripts/flashcards/build_recall_cards.py --subject history-aqa [--school-id X] [--dry]
  python scripts/flashcards/build_recall_cards.py --all-free [--dry]
"""
import io, json, os, re, sys, html, random, urllib.request, collections

U, K = os.environ["SUPABASE_URL"], os.environ["SUPABASE_SERVICE_KEY"]
H = {"apikey": K, "Authorization": "Bearer " + K, "Content-Type": "application/json"}
def get(path):
    req = urllib.request.Request(U + "/rest/v1/" + path, headers=H)
    return json.loads(urllib.request.urlopen(req, timeout=120).read())
def patch(path, body):
    req = urllib.request.Request(U + "/rest/v1/" + path, data=json.dumps(body).encode(), headers=dict(H, Prefer="return=minimal"), method="PATCH")
    urllib.request.urlopen(req, timeout=60).read()

def strip(s): return re.sub(r"\s+", " ", html.unescape(re.sub(r"<[^>]+>", " ", s or ""))).strip()

def sentences(content_html):
    """paragraph text split into sentences; headings, lists and captions left out"""
    out = []
    for p in re.findall(r"<p[^>]*>(.*?)</p>", content_html or "", re.S):
        t = strip(p)
        for s in re.split(r"(?<=[.!?])\s+(?=[A-Z‘“(])", t):
            s = s.strip()
            # never a sentence that names the exam board, points at the page, or talks about the course itself
            if 50 <= len(s) <= 220 and not s.endswith(":") and not re.search(r"\b(this lesson|below|above|next lesson|previous lesson|click|tap|AQA|Edexcel|Pearson|OCR|Eduqas|WJEC|the unit|this unit|the exam|examiners?|the spec|specification|mark scheme|marks?)\b", s, re.I):
                out.append(s)
    return out

def term_pattern(term):
    return re.compile(r"(?<![\w-])" + re.escape(term) + r"(?![\w-])", re.I)

def norm(s): return re.sub(r"[^a-z0-9 ]", "", strip(s).lower()).strip()

def build_for(lesson, rnd):
    # the curated deck's answers and questions: a term already tested there is not generated again
    cur = [c for c in (lesson.get("flashcard_questions") or []) if c]
    cur_answers = [norm(c.get("a") or c.get("answer") or "") for c in cur]
    cur_questions = [norm(c.get("q") or c.get("question") or "") for c in cur]
    def already_tested(term):
        t = norm(term)
        if not t: return True
        return any(t == a or (len(t) > 3 and t in a) for a in cur_answers) or any(len(t) > 3 and re.search(r"\b" + re.escape(t) + r"\b", q) for q in cur_questions)
    gl = [g for g in (lesson.get("glossary_terms") or []) if g.get("term") and g.get("definition") and 2 <= len(str(g["term"]).split()) <= 4 or (g.get("term") and g.get("definition") and len(str(g["term"])) >= 4)]
    gl = [g for g in gl if 15 <= len(strip(g["definition"])) <= 220 and len(strip(g["term"])) <= 40
          and not re.search(r"\b(AQA|Edexcel|Pearson|OCR|Eduqas|WJEC|examiners?|mark scheme)\b", strip(g["term"]) + " " + strip(g["definition"]), re.I)]
    gl = [g for g in gl if not already_tested(g["term"])]
    sents = sentences(lesson.get("content_html"))
    cards = []
    rnd.shuffle(gl)
    # term -> definition, definition -> term: different terms for each direction where we can
    for g in gl[:1]:
        cards.append({"kind": "term", "front": strip(g["term"]), "answer": strip(g["definition"]), "src": "glossary"})
    for g in (gl[1:2] if len(gl) >= 2 else gl[:1]):
        cards.append({"kind": "definition", "front": strip(g["definition"]), "answer": strip(g["term"]), "src": "glossary"})
    # cloze: a sentence that contains a glossary term exactly once, the term not at the very start
    used = set(); cl = []
    for g in gl:
        term = strip(g["term"]); pat = term_pattern(term)
        for s in sents:
            if s in used: continue
            hits = pat.findall(s)
            if len(hits) != 1: continue
            m = pat.search(s)
            if m.start() < 3: continue
            gap = s[:m.start()] + "____" + s[m.end():]
            cl.append({"kind": "cloze", "front": gap, "answer": m.group(0), "src": "sentence"}); used.add(s); break
        if len(cl) >= 1: break
    # a number or year gap, for the dates-and-figures memory the exams reward
    if len(cl) < 2:
        for s in sents:
            if s in used: continue
            nums = list(re.finditer(r"(?<![\w.])(1[5-9]\d\d|20[0-2]\d|\d{1,3}(?:,\d{3})+|\d+(?:\.\d+)?%|\d+(?:\.\d+)?\s?(?:million|billion|km|kg|m|cm|mm|°C|kJ|N|V|A|Hz))(?![\w.])", s))
            if len(nums) != 1: continue
            m = nums[0]
            cl.append({"kind": "cloze", "front": s[:m.start()] + "____" + s[m.end():], "answer": m.group(0), "src": "sentence"}); used.add(s); break
    return cards + cl[:2]

def main():
    a = sys.argv[1:]
    dry = "--dry" in a
    school = a[a.index("--school-id") + 1] if "--school-id" in a else None
    subjects = []
    if "--all-free" in a:
        subjects = [s["slug"] for s in get("subjects?select=slug&school_id=is.null&status=eq.live&order=slug")]
    elif "--subject" in a:
        subjects = [a[a.index("--subject") + 1]]
    else:
        print(__doc__); return
    rnd = random.Random(19)
    totals = collections.Counter()
    for slug in subjects:
        sch = ("eq." + school) if school else "is.null"
        rows = get("lessons?select=id,title,lesson_number,content_html,glossary_terms,flashcard_questions,units!inner(slug,subjects!inner(slug,school_id))&units.subjects.slug=eq.%s&units.subjects.school_id=%s&status=eq.live&is_listening=eq.false&limit=2000" % (slug, sch))
        n = 0
        for l in rows:
            if not l.get("content_html"): continue
            cards = build_for(l, rnd)
            if not cards: continue
            n += len(cards); totals.update(c["kind"] for c in cards)
            if dry:
                if n <= 12: [print("  ", slug, l["units"]["slug"], l["lesson_number"], "|", c["kind"], "|", c["front"][:90], "->", c["answer"][:50]) for c in cards]
            else:
                patch("lessons?id=eq." + l["id"], {"recall_cards": cards})
        print("%-40s lessons %3d cards %4d" % (slug, len(rows), n))
    print("totals", dict(totals), "(dry run, nothing written)" if dry else "(written)")

if __name__ == "__main__":
    main()
