"""Clone revision-technique guides from Food Prep (Eduqas) to Food Prep (AQA).

Same subject, same neutral naming ("Food Preparation and Nutrition"), both
free-tier (school_id NULL) — so the only change needed is the /guide/ nav-link
slug. Subject title and food-specific worked examples carry over verbatim.

Idempotent: skips any slug already present on the AQA subject.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from lib.supabase_client import get_client

sb = get_client()

SRC_SLUG = "food-preparation-and-nutrition-eduqas"
DST_SLUG = "food-preparation-and-nutrition-aqa"

src_sid = sb.table("subjects").select("id").eq("slug", SRC_SLUG).is_("school_id", "null").single().execute().data["id"]
dst_sid = sb.table("subjects").select("id").eq("slug", DST_SLUG).is_("school_id", "null").single().execute().data["id"]

src_guides = sb.table("guide_pages").select("*").eq("subject_id", src_sid).eq("guide_type", "revision-technique").execute().data
existing_dst = {g["slug"] for g in sb.table("guide_pages").select("slug").eq("subject_id", dst_sid).execute().data}

print(f"Source revision-technique guides ({SRC_SLUG}): {len(src_guides)}")

# Columns we must NOT copy verbatim (regenerated by DB / re-pointed)
DROP_COLS = {"id", "subject_id", "created_at", "updated_at"}

inserted = 0
skipped = 0
for g in src_guides:
    if g["slug"] in existing_dst:
        print(f"  SKIP existing: {g['slug']}")
        skipped += 1
        continue

    payload = {k: v for k, v in g.items() if k not in DROP_COLS}
    payload["subject_id"] = dst_sid
    # Re-point inter-guide nav links + any absolute guide URLs to the AQA slug
    if payload.get("content_html"):
        payload["content_html"] = payload["content_html"].replace(
            f"/guide/{SRC_SLUG}/", f"/guide/{DST_SLUG}/"
        )

    sb.table("guide_pages").insert(payload).execute()
    print(f"  inserted: {g['slug']}")
    inserted += 1

print(f"\n  Inserted: {inserted}, skipped: {skipped}")

# Verify
final = sb.table("guide_pages").select("slug, guide_type").eq("subject_id", dst_sid).execute().data
print(f"  Total guides now on {DST_SLUG}: {len(final)}")
for f in sorted(final, key=lambda x: x["slug"]):
    print(f"    [{f['guide_type']}] {f['slug']}")
